- name: prepare centos_mirrors file
  shell: "curl {{ apt_cacher_ng_centos_mirror_list_url }} | sed 's/^.*\"http:/http:/' | sed 's/\".*$//' | grep ^http >/etc/apt-cacher-ng/centos_mirrors"
  tags:
    - skip_ansible_lint

- name: Configure acng.conf.
  template:
    src: etc/apt-cacher-ng/acng.conf.j2
    dest: /etc/apt-cacher-ng/acng.conf
  notify:
    - restart apt-cacher-ng