- name: Define passthrough patterns
  lineinfile:
    path: /etc/apt-cacher-ng/acng.conf
    line: "PassThroughPattern: {{ apt_cacher_ng_passthroughpattern }}"
  notify:
    - restart apt-cacher-ng
  when: apt_cacher_ng_passthroughpattern is defined

- name: Configure PrecacheFor.
  blockinfile:
    path: /etc/apt-cacher-ng/acng.conf
    state: "{{ 'present' if (apt_cacher_ng_precachefor | bool) else 'absent' }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK PrecacheFor"
    block: |
      PrecacheFor: {{ apt_cacher_ng_precachefor }}
  notify:
    - restart apt-cacher-ng