- name: prepare centos_mirrors file
  shell: "curl {{ apt_cacher_ng_centos_mirror_list_url }} | sed 's/^.*\"http:/http:/' | sed 's/\".*$//' | grep ^http >/etc/apt-cacher-ng/centos_mirrors"
  tags:
    - skip_ansible_lint

- name: Configure acng.conf.
  template:
    src: etc/apt-cacher-ng/acng.conf.j2
    dest: /etc/apt-cacher-ng/acng.conf
    mode: 644
  notify:
    - restart apt-cacher-ng

- name: Configure hostname in cronjob.
  blockinfile:
    path: /etc/cron.daily/apt-cacher-ng
    insertafter: "# export HOSTNAME"
    marker: "# {mark} ANSIBLE MANAGED BLOCK hostname"
    mode: 644
    block: |
      HOSTNAME={{ apt_cacher_ng_hostname }}
      export HOSTNAME