---
- name: prepare centos_mirrors file
  shell: >
    curl {{ apt_cacher_ng_centos_mirror_list_url }} |
    sed 's/^.*\"http:/http:/' |
    sed 's/\".*$//' |
    grep ^http >/etc/apt-cacher-ng/centos_mirrors"
  tags:
    - skip_ansible_lint

- name: Configure acng.conf.
  template:
    src: etc/apt-cacher-ng/acng.conf.j2
    dest: /etc/apt-cacher-ng/acng.conf
    mode: 0644
  notify:
    - restart apt-cacher-ng

- name: Configure cronjob.
  blockinfile:
    path: /etc/cron.daily/apt-cacher-ng
    insertafter: "# export HOSTNAME"
    marker: "# {mark} ANSIBLE MANAGED BLOCK hostname"
    mode: 0644
    block: |
      HOSTNAME={{ apt_cacher_ng_hostname }}
      export HOSTNAME
      {% if apt_cacher_ng_acngreq is defined %}
      ACNGREQ={{ apt_cacher_ng_acngreq }}
      export ACNGREQ
      {% endif %}
